name: Python SDK Tests

on:
  push:
  pull_request:

jobs:
  test-python-sdk:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: npm ci

      - name: Test python-sdk
        run: make test-python-sdk

      - name: Reposity contains actual python-sdk version
        run: |
          diff_result=$(git diff --exit-code --name-only example/python/aidbox || true)

          if [ -z "$diff_result" ]; then
            echo "✅ Generated SDK is identical to the one stored in repository."
          else
            echo "❌ Generated SDK differs from the one stored in repository."
            echo "Differences:"
            git diff example/python/aidbox
            exit 1
          fi
