name: typescript-sdk

on:
  push:
  pull_request:

jobs:
  test-typescript-sdk:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Test typescript-sdk
        run: make test-typescript-sdk

      - name: Repository contains actual typescript-sdk version
        run: |
          diff_result=$(git diff --exit-code --name-only example/typescript/fhirsdk || true)

          if [ -z "$diff_result" ]; then
            echo "✅ Generated SDK is identical to the one stored in repository."
          else
            echo "❌ Generated SDK differs from the one stored in repository."
            echo "Differences:"
            git diff example/typescript/fhirsdk
            exit 1
          fi
